"""Horizon cost minimization: DP (charge/idle) then offpeak fill then ranked export.

``optimize_horizon`` is the public pipeline. ``run_horizon_dp`` does not assign
battery→grid export; that is ``plan_battery_grid_export``.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

from .plan_charge import (
    battery_grid_charge_step_ac,
    enforce_min_hourly_battery_grid_limits,
    grid_charge_ac_kw,
    offpeak_min_block_charge_is_worth,
    plan_battery_grid_charge,
)
from .plan_dp import (
    CONTROL_DEDUP_DECIMALS,
    DP_COST_INF,
    DP_SOC_BIN_KWH,
    EXPORT_MIN_FRAC,
    EXPORT_POWER_FRACS,
    control_options,
    run_horizon_dp,
    tail_start_hour,
)
from .plan_export import (
    BatteryGridExportHourClaim,
    G12Tariff,
    assign_ranked_battery_export,
    battery_export_break_even_rce,
    battery_export_step_allowed,
    evening_export_window_hours,
    export_credit_price,
    export_span_candidates,
    export_window_roles,
    g12_tariff_from_cfg,
    hold_soc_for_later_battery_grid_export_claims,
    hour_rce_rating,
    hour_rce_rating_5_groszy,
    hourly_avg_rce,
    max_battery_export_kwh,
    optimization_battery_export_value,
    pick_next_export_hour,
    plan_battery_grid_export,
    plan_hour_battery_grid_export_claim,
    rank_hours_by_avg_rce,
    round_rce_5_groszy,
    sale_windows,
    trim_remaining_after_failed_export_edge,
)
from .plan_physics import (
    HourControl,
    HourPhysics,
    apply_grid_charge_ac,
    eps_step_kwh,
    simulate_hour,
    slots_per_hour_from_scale,
)
from .plan_reserve import (
    apply_post_discharge_reserve_floor,
    build_extended_buy_for_reserve,
    build_extended_pv_load_for_reserve,
    grid_charge_target_soc_kwh_from_step,
    morning_cover_bound_from_hour_buys,
    post_discharge_reserve_soc_kwh,
    pv_cover_ends_overnight_need,
    reserve_soc_kwh_from_step,
    reserve_soc_per_step,
    tomorrow_lookahead_start_hour,
)
from .plan_spill import pv_load_energy_split

__all__ = [
    "BatteryGridExportHourClaim",
    "DP_COST_INF",
    "G12Tariff",
    "HourControl",
    "HourPhysics",
    "apply_grid_charge_ac",
    "apply_post_discharge_reserve_floor",
    "battery_export_break_even_rce",
    "battery_export_step_allowed",
    "battery_grid_charge_step_ac",
    "build_extended_buy_for_reserve",
    "build_extended_pv_load_for_reserve",
    "control_options",
    "enforce_min_hourly_battery_grid_limits",
    "eps_step_kwh",
    "evening_export_window_hours",
    "export_credit_price",
    "export_span_candidates",
    "export_window_roles",
    "g12_tariff_from_cfg",
    "grid_charge_ac_kw",
    "grid_charge_target_soc_kwh_from_step",
    "hold_soc_for_later_battery_grid_export_claims",
    "hour_rce_rating",
    "hour_rce_rating_5_groszy",
    "hourly_avg_rce",
    "morning_cover_bound_from_hour_buys",
    "offpeak_min_block_charge_is_worth",
    "optimization_battery_export_value",
    "optimize_horizon",
    "pick_next_export_hour",
    "plan_battery_grid_charge",
    "plan_battery_grid_export",
    "plan_hour_battery_grid_export_claim",
    "post_discharge_reserve_soc_kwh",
    "pv_cover_ends_overnight_need",
    "pv_load_energy_split",
    "rank_hours_by_avg_rce",
    "reserve_soc_kwh_from_step",
    "reserve_soc_per_step",
    "round_rce_5_groszy",
    "sale_windows",
    "simulate_hour",
    "slots_per_hour_from_scale",
    "tail_start_hour",
    "tomorrow_lookahead_start_hour",
    "trim_remaining_after_failed_export_edge",
]


def optimize_horizon(
    *,
    steps: int,
    pv_series: list[float],
    load_series: list[float],
    buy_prices: list[float],
    rce_series: list[float | None],
    initial_soc_kwh: float,
    cfg: dict,
    params: dict[str, float | int],
    end_dt: datetime,
    today_date,
    rce_map: dict[tuple[str, int], float | None],
    forecast: dict[str, Any] | None = None,
    step_scale: float = 1.0,
    rce_step_offset: int = 0,
    front_load_skip_leading_slots: int | None = None,
    skip_export_hours: set[int] | None = None,
) -> list[HourControl]:
    """DP charge/idle, then offpeak grid charge, then ranked battery export."""
    dp = run_horizon_dp(
        steps=steps,
        pv_series=pv_series,
        load_series=load_series,
        buy_prices=buy_prices,
        rce_series=rce_series,
        initial_soc_kwh=initial_soc_kwh,
        cfg=cfg,
        params=params,
        end_dt=end_dt,
        today_date=today_date,
        rce_map=rce_map,
        forecast=forecast,
        step_scale=step_scale,
        rce_step_offset=rce_step_offset,
        front_load_skip_leading_slots=front_load_skip_leading_slots,
        skip_export_hours=skip_export_hours,
    )
    if dp.skip_post:
        return dp.controls

    controls = plan_battery_grid_charge(
        dp.controls,
        pv_series=pv_series,
        load_series=load_series,
        buy_prices=buy_prices,
        offpeak_buy=dp.offpeak_buy,
        charge_targets=dp.charge_targets,
        initial_soc_kwh=initial_soc_kwh,
        battery_cap=dp.battery_cap,
        min_kwh=dp.min_kwh,
        charge_ac_step=dp.charge_ac_step,
        discharge_dc_step=dp.discharge_dc_step,
        inverter_ac_step=dp.inverter_ac_step,
        eta_grid=dp.eta_grid,
        eta_out=dp.eta_out,
        eta_pv_load=dp.eta_pv_load,
        eta_pv_grid=dp.eta_pv_grid,
        eta_pv_battery=dp.eta_pv_battery,
        eps_step=dp.eps_step,
        reserves=dp.reserves,
        step_scale=step_scale,
        skip_leading_slots=front_load_skip_leading_slots,
        min_block_minutes=dp.min_block_minutes,
        min_hourly_kwh=dp.min_hourly_transfer,
    )
    controls = plan_battery_grid_export(
        controls,
        steps=steps,
        pv_series=pv_series,
        load_series=load_series,
        rce_series=rce_series,
        rce_step_offset=rce_step_offset,
        step_scale=step_scale,
        initial_soc_kwh=initial_soc_kwh,
        battery_cap=dp.battery_cap,
        min_kwh=dp.min_kwh,
        discharge_dc_step=dp.discharge_dc_step,
        inverter_ac_step=dp.inverter_ac_step,
        eta_grid=dp.eta_grid,
        eta_out=dp.eta_out,
        eta_pv_load=dp.eta_pv_load,
        eta_pv_grid=dp.eta_pv_grid,
        eta_pv_battery=dp.eta_pv_battery,
        eps_step=dp.eps_step,
        reserves=dp.reserves,
        export_floor=dp.export_floor,
        min_hourly_kwh=dp.min_hourly_transfer,
        export_window_start_hour=dp.window_start,
        skip_export_hours=skip_export_hours,
    )
    return enforce_min_hourly_battery_grid_limits(
        controls,
        rce_step_offset=rce_step_offset,
        step_scale=step_scale,
        min_hourly_kwh=dp.min_hourly_transfer,
        epsilon=dp.eps_step,
    )
